[project]
name = "harv-experiments"
version = "0.1.0"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = [
    "harv",
    "kepmodel",
]

[project.optional-dependencies]
mpi = [
    "mpi4py>=4.1.2",
]

[dependency-groups]
dev = [
  "ruff",
  "pre-commit",
]

test = [
  "pytest",
]

docs = [
]

# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

# [tool.hatch.metadata]
# allow-direct-references = true

# [tool.hatch.build.targets.wheel]
# packages = ["src/TODO"]

[tool.ruff]
[tool.ruff.lint.per-file-ignores]
"scripts/*" = ["E741"]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
harv = { git = "https://github.com/adrn/harv.git", rev = "periodogram" }
kepmodel = { git = "https://gitlab.unige.ch/delisle/kepmodel.git" }
